trigger:
- nginx

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Bash@3
      inputs:
        filePath: 'bash.sh'